version: "3.9"

networks:
  cup_movie_net:

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      REDIS_URL: redis://redis:6379
      CACHE_TTL: 60
      TVMAZE_BASE_URL: https://api.tvmaze.com
    depends_on:
      - redis
    networks:
      - cup_movie_net

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - cup_movie_net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - SEARCH_DELAY=500
        - API_ROOT_URL=/api
    expose:
      - 80
    ports:
      - "3000:80"
    networks:
      - cup_movie_net
